export class MapSurface {
  constructor(container,{onPoint=()=>{},onPick=()=>{},imageRoot='maps/'}={}){
    this.el=container;this.onPoint=onPoint;this.onPick=onPick;this.imageRoot=imageRoot;this.points=[];this.scale=1;this.x=0;this.y=0;this.pointers=new Map();this.selecting=false;this.serial=0;
    this.world=document.createElement('div');this.world.className='map-world';this.img=document.createElement('img');this.img.className='map-image';this.img.alt='地图';this.img.draggable=false;this.layer=document.createElement('div');this.layer.className='map-markers';this.world.append(this.img,this.layer);this.el.append(this.world);
    this.message=document.createElement('p');this.message.className='map-message';this.message.setAttribute('role','status');this.el.append(this.message);
    this.controls=document.createElement('div');this.controls.className='map-controls';for(const [label,text,fn]of [['放大','＋',()=>this.zoom(1.4)],['缩小','−',()=>this.zoom(1/1.4)],['重置视角','⟲',()=>this.fit()]]){const b=document.createElement('button');b.type='button';b.textContent=text;b.title=label;b.setAttribute('aria-label',label);b.onclick=fn;this.controls.append(b);}this.el.append(this.controls);
    this.el.addEventListener('wheel',e=>{if(e.target.closest('.map-controls'))return;e.preventDefault();const r=this.el.getBoundingClientRect();this.zoom(e.deltaY>0?1/1.15:1.15,e.clientX-r.left,e.clientY-r.top);},{passive:false});
    // Keep browser image/text dragging from taking over the map gesture.
    this.el.addEventListener('dragstart',e=>e.preventDefault());
    this.el.addEventListener('pointerdown',e=>{if(e.target.closest('button')&&!e.target.closest('[data-draft]'))return;if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();this.el.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});this.dragPin=!!e.target.closest('[data-draft]');this.start={x:e.clientX,y:e.clientY,ox:this.x,oy:this.y};this.moved=false;if(this.pointers.size===2){this.moved=true;this.pinch=this.pinchState();}this.el.classList.add('dragging');});
    this.el.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===2){const n=this.pinchState();if(this.pinch){const rect=this.el.getBoundingClientRect();this.zoom(n.dist/this.pinch.dist,this.pinch.x-rect.left,this.pinch.y-rect.top);this.x+=n.x-this.pinch.x;this.y+=n.y-this.pinch.y;this.apply();}this.pinch=n;this.moved=true;return;}
      const dx=e.clientX-this.start.x,dy=e.clientY-this.start.y;if(Math.hypot(dx,dy)>4)this.moved=true;if(this.dragPin){if(this.moved)this.pick(e.clientX,e.clientY);}else if(this.moved){this.x=this.start.ox+dx;this.y=this.start.oy+dy;this.clamp();this.apply();}});
    const end=e=>{if(!this.pointers.has(e.pointerId))return;const click=!this.moved&&this.pointers.size===1;this.pointers.delete(e.pointerId);if(this.pointers.size===1){const p=[...this.pointers.values()][0];this.start={x:p.x,y:p.y,ox:this.x,oy:this.y};this.moved=true;}if(!this.pointers.size){this.el.classList.remove('dragging');this.pinch=null;if(click&&this.selecting&&e.type!=='pointercancel')this.pick(e.clientX,e.clientY);}};
    this.el.addEventListener('pointerup',end);this.el.addEventListener('pointercancel',end);this.el.addEventListener('lostpointercapture',end);
    this.observer=new ResizeObserver(()=>{if(this.img.naturalWidth)this.fit();});this.observer.observe(this.el);
  }
  pinchState(){const [a,b]=[...this.pointers.values()];return {dist:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),x:(a.x+b.x)/2,y:(a.y+b.y)/2};}
  async load(id,points=[]){this.id=id;this.points=points;this.selected=null;const serial=++this.serial;this.message.textContent='正在加载地图…';this.layer.replaceChildren();const image=new Image();image.src=this.imageRoot+id+'.png';try{await image.decode();if(serial!==this.serial)return;this.img.src=image.src;this.img.alt=id+' 地图';this.nw=image.naturalWidth;this.nh=image.naturalHeight;this.message.textContent='';this.fit();}catch{if(serial===this.serial)this.message.textContent='地图加载失败，请刷新重试';}}
  fit(){if(!this.nw)return;const w=this.el.clientWidth,h=this.el.clientHeight;const ratio=Math.min(w/this.nw,h/this.nh)*.94;this.w=this.nw*ratio;this.h=this.nh*ratio;this.world.style.width=this.w+'px';this.world.style.height=this.h+'px';this.scale=1;this.x=(w-this.w)/2;this.y=(h-this.h)/2;this.apply();this.render();}
  clamp(){const w=this.el.clientWidth,h=this.el.clientHeight,cw=this.w*this.scale,ch=this.h*this.scale;this.x=cw<w?(w-cw)/2:Math.max(w-cw-80,Math.min(80,this.x));this.y=ch<h?(h-ch)/2:Math.max(h-ch-80,Math.min(80,this.y));}
  markerScale(){return Math.min(this.scale,1.6);}
  apply(){this.world.style.transform=`translate(${this.x}px,${this.y}px) scale(${this.scale})`;this.world.style.setProperty('--inverse',this.markerScale()/this.scale);}
  zoom(f,cx=this.el.clientWidth/2,cy=this.el.clientHeight/2){if(!this.w)return;const next=Math.max(.5,Math.min(6,this.scale*f)),ratio=next/this.scale;this.x=cx-(cx-this.x)*ratio;this.y=cy-(cy-this.y)*ratio;this.scale=next;this.clamp();this.apply();this.render();}
  pick(cx,cy){const r=this.el.getBoundingClientRect(),x=(cx-r.left-this.x)/this.scale/this.w,y=(cy-r.top-this.y)/this.scale/this.h;if(x<0||x>1||y<0||y>1)return;this.selected={x,y};this.render();this.onPick(this.selected);}
  setSelection(pos,active){this.selected=pos;this.selecting=active;this.el.classList.toggle('selecting',active);this.render();}
  setPoints(points){this.points=points;this.render();}
  render(){this.layer.replaceChildren();if(!this.w)return;const groups=[];for(const p of this.points){const group=groups.find(g=>Math.hypot((g[0].x-p.x)*this.w*this.scale,(g[0].y-p.y)*this.h*this.scale)<26*this.markerScale());if(group)group.push(p);else groups.push([p]);}
    for(const g of groups){const b=document.createElement('button');b.type='button';b.className='map-dot '+(g.length>1?'combined':g[0].side);b.style.left=(g.reduce((s,p)=>s+p.x,0)/g.length*100)+'%';b.style.top=(g.reduce((s,p)=>s+p.y,0)/g.length*100)+'%';b.textContent=g.length>1?g.length:'';b.title=g.map(p=>p.name).join(' / ');b.setAttribute('aria-label',b.title);b.tabIndex=this.selecting?-1:0;b.onclick=()=>{if(!this.selecting)this.onPoint(g);};this.layer.append(b);}
    if(this.selected){const b=document.createElement('button');b.type='button';b.dataset.draft='true';b.className='map-dot chosen';b.style.left=this.selected.x*100+'%';b.style.top=this.selected.y*100+'%';b.title='当前站位，可拖动调整';b.setAttribute('aria-label',b.title);this.layer.append(b);}
  }
}

export function node(tag,props={},children=[]){const e=document.createElement(tag);for(const [k,v]of Object.entries(props)){if(k==='text')e.textContent=v;else if(k==='class')e.className=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2),v);else if(v!==undefined)e.setAttribute(k,v);}for(const child of children)e.append(child);return e;}
export function lightbox(src,caption='截图'){const dialog=node('dialog',{class:'lightbox'}),close=node('button',{text:'关闭 ×',class:'lightbox-close',onclick:()=>dialog.close()});dialog.append(close,node('img',{src,alt:caption}));document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
